services:
  db:
    image: postgres:15-alpine
    container_name: sienge_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sienge_data}
      POSTGRES_USER: ${POSTGRES_USER:-sienge_app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5432}:5432"  # Expõe PostgreSQL para conexões remotas
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./migrations/001_create_tables.sql:/docker-entrypoint-initdb.d/02-create_tables.sql:ro
      - ./migrations/002_add_sync_date.sql:/docker-entrypoint-initdb.d/03-add_sync_date.sql:ro
      - ./migrations/003_add_sync_control.sql:/docker-entrypoint-initdb.d/04-add_sync_control.sql:ro
    networks:
      - sienge_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sienge_app} -d ${POSTGRES_DB:-sienge_data}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  sync:
    build: .
    container_name: sienge_sync
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sienge_data}
      POSTGRES_USER: ${POSTGRES_USER:-sienge_app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SIENGE_SUBDOMAIN: ${SIENGE_SUBDOMAIN}
      SIENGE_USERNAME: ${SIENGE_USERNAME}
      SIENGE_PASSWORD_ABF: ${SIENGE_PASSWORD_ABF}
      SYNC_START_DATE: ${SYNC_START_DATE:-2024-01-01}
      SYNC_END_DATE: ${SYNC_END_DATE:-2024-12-31}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - sienge_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api:
    build: ./api
    container_name: sienge_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sienge_data}
      POSTGRES_USER: ${POSTGRES_USER:-sienge_app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    networks:
      - sienge_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 3
      start_period: 20s
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: sienge_cloudbeaver
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    environment:
      CB_SERVER_NAME: Sienge Financial DB
    networks:
      - sienge_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  sienge_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  cloudbeaver_data:
    driver: local